"""Generate thin multi-agent adapters from AGENTS.md (source of truth)."""
from __future__ import annotations

from pathlib import Path

GENERATED = "<!-- Generated by scripts/lib/agent_adapters.py — edit AGENTS.md, then re-sync. -->"

CURSOR_RULE = """---
description: Canonical agent spec pointer (synced from AGENTS.md)
alwaysApply: true
---

# Main (AGENTS.md adapter)

Read `AGENTS.md` before editing. It is the source of truth for architecture, gates, and session protocol.

## Test-first

Every feature task must include automated tests, or the feature spec must state why tests are not feasible and name the fallback validation command.

## Invariants

- FOSS MIT default; no proprietary SDKs on the FOSS production path
- Max 300 lines static data (UI + i18n), 150 lines pure logic
- Conventional Commits; never commit secrets or `.env`
- Sequential BUILD_PLAN before Parallel; 🔲 / ✅ / ❌ status markers
- Destructive ops (`git push`, production deploys) need `[HUMAN]` approval

## Commands

Run `bash scripts/verify.sh` before marking a BUILD_PLAN row complete.

`python3 scripts/agent-run.py validate-bootstrap --quick`
`python3 scripts/agent-run.py watch-agent-gates --once --autofix`
"""

CLAUDE = f"""{GENERATED}

# Claude Code instructions

This project uses `AGENTS.md` as the canonical agent specification. Read it first, then `docs/START_HERE.md` and `docs/CURSOR_MODES.md`.

## Test-first

Do not complete a feature task without corresponding tests, or an explicit justification plus fallback validation command in `docs/features/{{name}}.md` / `docs/spec.md`.

## Do

- Follow BUILD_PLAN Sequential then Parallel
- Run `python3 scripts/agent-run.py watch-agent-gates --once --autofix` after AGENT steps
- Keep edits inside the active feature container

## Do not

- Commit secrets, `.env`, or skip hooks
- Push or deploy without human approval
- Blind-overwrite child `AGENTS.md` on template upgrade
"""

COPILOT = f"""{GENERATED}

# GitHub Copilot instructions

Canonical spec: `AGENTS.md`. Router: `docs/START_HERE.md`. Modes: `docs/CURSOR_MODES.md`.

- Test-first: every feature change ships tests or a written fallback validation command
- Type-safe boundaries; validate untrusted input
- Conventional Commits; no secrets in the tree
- Prefer vertical slices under `examples/{{stack}}/` plus `docs/features/{{name}}.md`
- Use 🔲 / ✅ / ❌ (not GitHub `- [ ]` checkboxes) on repo checklists
"""


def write_adapters(root: Path, enabled: dict[str, bool] | None = None) -> list[Path]:
    flags = enabled or {}
    written: list[Path] = []
    mapping = (
        ("cursor_rules", Path(".cursor/rules/main.mdc"), CURSOR_RULE),
        ("claude", Path("CLAUDE.md"), CLAUDE),
        ("copilot", Path(".github/copilot-instructions.md"), COPILOT),
    )
    for key, rel, body in mapping:
        if flags.get(key, True) is False:
            continue
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(body.lstrip() + "\n", encoding="utf-8")
        written.append(path)
    return written
